### ISSUE TITLE
ModuleNotFoundError: No module named 'qdarktheme'

### ISSUE THREAD

**Issue by MrHappy** [blueboy-tm/LinuxBacklightManager#2]
Installer didn't work for me (see #1), so compiled it and ran installer.
Maybe add a warning that the system autmatically reboots?

After searching the source I found where the application was placed and ran it.
It gave me the error ModuleNotFoundError: No module named 'qdarktheme'. Although I installed pyqtdarktheme (and pyqt-darktheme, to be sure).
What is missing?

**Comment by blueboy-tm** [comment]
you should install requirements
check https://github.com/blueboy-tm/LinuxBacklightManager#compile-the-code
virtualenv venv 
source venv/bin/activate
pip install -r requirements.txt
cd compile
bash appcompile
bash installercompile
sudo ./installer
------------------------------------
or download https://github.com/blueboy-tm/LinuxBacklightManager/releases/download/1.0.1/installer.tar.gz
and run
sudo ./installer

**Comment by MrHappy** [comment]
I followed the commands above and got an error:
`pip install -r requirements.txt`
`Collecting altgraph==0.17.2
  Using cached altgraph-0.17.2-py2.py3-none-any.whl (21 kB)
ERROR: Could not find a version that satisfies the requirement pkg_resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg_resources==0.0.0`

**Comment by MrHappy** [comment]
Removed that line from requirements.txt and update pyinstaller to latest version and now it works.
Thanks!
